modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="moreblocks"
version="2.0.0"
displayName="More Blocks"
credits="Mod Credits to SMLkaiellis08"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="SMLkaiellis08"
description='''
More blocks to add to the surivival world
'''

[[dependencies.moreblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




